version: "3.8"

services:
  projektpilkarz:
    image: brestmoor/private:projektpilkarz-a5c43e0
    pull_policy: always
    restart: always
    networks:
      - caddy_network

  caddy_reverse_proxy:
    image: caddy:latest
    restart: always
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./certs:/etc/ssl/certs/custom
      - ./private:/etc/ssl/private/custom
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - "80:80"
      - "443:443"
    networks:
      - caddy_network
    depends_on:
      - projektpilkarz

  dozzle:
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./dozzle:/data
    ports:
      - 8080:8080
    environment:
      DOZZLE_AUTH_PROVIDER: simple

networks:
  caddy_network:

volumes:
  caddy_data:
  caddy_config:
